package com.bahardev.submissioncompose.model

object AnimeData {
    val anime = listOf(
        Anime("1", "One Piece", "https://cdn.myanimelist.net/images/anime/1011/120243l.jpg", "ada seorang bajak laut terkenal di seluruh lautan bernama Gol D. Roger. Ia merupakan seorang raja bajak laut yang telah berlayar mengarungi seluruh Grand Line, sayangnya ia ditangkap pemerintah dan telah dieksekusi mati. Sesaat sebelum kematiannya, Ia mengumumkan kepada dunia bahwa dirinya menyimpan sebuah harta karun bernama One Piece, sebuah harta karun yang kini menjadi incaran seluruh bajak laut yang ada di dunia.\n"),
        Anime("2", "Yofukashi no Uta", "https://i.ibb.co/VSxk2Qj/portada-yofukashi-no-uta-13.jpg", "Kou Yamori tampak seperti siswa sekolah menengah biasa di permukaan. Relatif pandai belajar dan ramah dengan teman-teman sekelasnya, dia berusaha keras untuk mempertahankan fasad ini. Suatu hari, bagaimanapun, ia memutuskan untuk berhenti berpura-pura dan berhenti sekolah, mengembangkan insomnia sebagai akibat tidak memiliki outlet siang hari untuk energinya. Saat berjalan-jalan sendirian di malam hari, dia merasa sedikit lebih baik, meskipun dia sadar bahwa ketidakmampuannya untuk tidur harus dianggap sebagai masalah serius."),
        Anime("3", "Vanitas no Karte", "https://m.media-amazon.com/images/M/MV5BYzM4ODUyNzItMjM0NC00MjVlLWFhZWMtMmFlNGFiYTQxZmVkXkEyXkFqcGdeQXVyMzgxODM4NjM@._V1_.jpg", "Kurma kedua Vanitas no Carte . Ini Paris abad ke-19, dan vampir muda Noé berburu Kitab Vanitas. Diserang oleh vampir yang gila, seorang dokter manusia bernama Vanitas menggoda Noé dengan perang salib gila untuk \"menyembuhkan\" seluruh ras vampir."),
        Anime("4", "Chikyuugai Shounen Shoujo", "https://somoskudasai.com/wp-content/uploads/2021/12/portada_chikyuugai-shounen-shoujo-4.jpg", "Pada tahun 2045, Internet dan kecerdasan buatan telah menyebar luas di luar angkasa. Setelah kecelakaan besar di stasiun luar angkasa, sekelompok anak-anak tertinggal. Menggunakan pita sempit dan SNS, AI dengan kecerdasan rendah, dan drone yang dikendalikan ponsel cerdas, mereka mengatasi banyak krisis."),
        Anime("5", "Dr Stone", "https://i.ibb.co/J5b4zKK/images.jpg", "Suatu hari, Taiju Oki telah bersiap untuk menyatakan cinta-nya kepada gadis yang sudah ia sukai sejak lima tahun lalu. Ketika ia ingin menyatakan cinta-nya, secara tiba-tiba muncul cahaya aneh yang menyinari bumi. Cahaya itu mampu menembus segala bentuk bangunan ataupun dinding dan membuat orang yang terkena cahaya tersebut menjadi batu. Setelah Taiju terkena cahaya tersebut, batu yang ada di dirinya mulai retak dan hancur. Ia pun terkejut, pasalnya peradabannya saat itu telah banyak berubah. Bumi ini hanya di huni oleh tumbuhan dan binatang. Sampai suatu hari, Taiju bertemu dengan Senkuu. Senkuu merupakan teman sekelas Taiju yang mempunya pengetahuan di bidang sains.\n"),
        Anime("6", "Hello World", "https://i.ibb.co/vxM89HF/EVYln-Gi-UMAAk-Wy0.jpg", "Tahun 2027, dan kota Kyoto telah mengalami kemajuan teknologi yang luar biasa. Di dalam kota hidup Naomi Katagaki, seorang anak laki-laki yang canggung secara sosial dan tertutup dengan cinta untuk buku, dan Ruri Ichigyou, seorang gadis dengan kepribadian dingin yang sering blak-blakan dengan orang-orang, tetapi berbagi cintanya untuk membaca. Meski memiliki minat yang sama, Naomi takut untuk mendekati Ruri karena sifatnya yang tidak ramah. Suatu hari, saat Naomi keluar untuk berjalan-jalan, aurora merah tua menembus langit untuk sesaat sebelum menghilang. Tak lama setelah itu, dia melihat seekor gagak berkaki tiga dan seorang pria berkerudung misterius yang mengungkapkan dirinya sebagai Naomi dari 10 tahun ke depan, menjelaskan bahwa dia datang untuk mengubah peristiwa tragis yang akan terjadi pada Ruri tak lama setelah mereka mulai berkencan. Awalnya mengambil kata-katanya dengan sebutir garam, Naomi saat ini mengikuti instruksi dirinya di masa depan dan mulai semakin dekat dengan Ruri, bertekad untuk menyelamatkannya. Hello World berfokus pada Naomi saat ini bersama dirinya dari 10 tahun ke depan. Dengan bantuan dirinya di masa depan, Naomi memulai persiapannya untuk menyelamatkan Ruri. Akankah dia mampu mengubah masa depan?\n"),
        Anime("7", "One Punch Man Season 1", "https://cdn.myanimelist.net/images/anime/7/72533l.jpg?_gl=1*197qzgv*_ga*MTA1NTYwNDQwOC4xNjU4MTE4MjEz*_ga_26FEP9527K*MTY1ODEyMTQ1My4yLjEuMTY1ODEyMTQ5OC4xNQ..", "Anime One Punch Man menceritakan seorang pemuda yang ingin menjadi pahlawan, ia bernama Saitama. Selama tiga tahun Saitama berlatih tanpa henti sampai-sampai ia kehilangan rambutnya sehingga menjadi Botak. Sekarang Saitama sangat kuat dan sudah siap untuk menjadi Pahlawan, begitu banyak musuh yang sudah dikalahkannya. Bahkan ia hanya mengalahkan musuhnya dengan hanya 1 kali pukulan (One Punch). Sehingga semua itu membuatnya bosan, karena terlalu mudah melawan penjahat atau monster. Namun Saitama belum mengetahui bahwa belum ada yang mengakuinya sebagai pahlawan. Suatu hari Saitama kedatangan Genos, seorang Cyborg 19 tahun yang ingin menjadi murid Saitama setelah melihat kekuatannya yang hebat. Genos memberitahukan kepada Saitama cara untuk menjadi Pahlawan. Yaitu dengan bergabung ke Asosiasi Pahlawan untuk menjadi Pahlawan dan mendapatkan sertifikat yang akan di akui masyarakat sebagai pahlawan. Saitama akhirnya setuju untuk bergabung kedalam Asosiasi Pahlawan demi menggapai tujuannya menjadi pahlawan. Disinilah kisah One Punch Man bersama Saitama dan Genos dimulai."),
        Anime("8", "Mahoutsukai Reimeiki", "https://dafunda.com/wp-content/uploads/2022/03/New-Visual-Anime-Mahoutsukai-Reimeiki-800x1133.jpg", "Meskipun ia menghadiri Akademi Sihir Kerajaan di Kerajaan Wenias, Sable memiliki nilai terburuk di seluruh sekolah. Karena dia tidak memiliki ingatan tentang waktunya sebelum menghadiri institusi tersebut, ketika Kepala Sekolah Albus menugaskannya dengan rejimen pelatihan khusus di selatan, Sable dengan penuh semangat menerimanya. Di samping Penyihir Fajar, Roux Cristasse; Holt, seorang gadis manusia dengan tanduk; dan Kudd, seekor kadal Beastfallen, Sable harus membangun desa penyihir di wilayah di mana sentimen anti-penyihir tetap kuat. Selama perjalanan mereka, kuartet menghindari mantan anggota Dia Ignis Arbiter — sekelompok pemburu penyihir yang terkenal karena membunuh penyihir dan warga sipil. Lima tahun yang lalu, organisasi mereka dibubarkan dan diberi amnesti dengan berakhirnya perang antara Gereja dan penyihir, tetapi anggota mereka masih bertahan dan siap untuk menangkap penyihir yang mereka temui."),
        Anime("9", "Kaze no tani no Naushika", "https://1.bp.blogspot.com/-_BbMBuZRDnk/V5ecfimKjWI/AAAAAAAAhJs/QzawLq1OQUM955hos1VTFYBSlv1KSdmJgCLcB/s1600/01.jpg", "Seorang prajurit pecinta -damai, Princess Nausicaa, mati-matian berjuang untuk mencegah dua bangsa agar tak saling berperang dan menghancurkan mereka sendiri dan planet yang telah sekarat."),
        Anime("10", "Koe no Katachi BD Movie", "https://assets.kompasiana.com/items/album/2021/09/08/koe-no-katachi-netflix-1200-6138792e010190577f651952.jpg", "Koe no Katachi menceritakan tentang Ishida Shouya yang ketika dirinya menduduki bangku Sekolah Dasar (SD) sering membully kepada murid pindahan yang bernama Nishimiya Shouko yang ternyata mengidap tuna rungu (tuli). Bahkan bullyannya hingga membuat Shouko pindah lagi dari sekolah itu. Karena suatu insiden teman-teman Shouya mengetahui bahwa dirinya sering membully Shouko, hal itupun membuat teman-temannya balik membully Shouya hingga dirinya dikucilkan. Setelah SMA Shouya mulai menutup hatinya dengan rasa bersalah yang ia pendam dari SD. Hingga suatu hari dirinya dipertemukan lagi dengan Shouko, pertemuan itulah yang membuat Shouya mulai berubah. Mulai hari itu Shouya bertekad untuk memperbaiki kesalahan yang telah ia lakukan saat SD. Dan hari-harinya bersama Shouko pun dimulai.")
    )
}